		<div id="footer-container" class="container">
		<div id="footer">
		<ul class="col-list">
			<li>
			<h3>Project</h3>
			<ul class="link-list">
				<li>Overview</li>
				<li>Tutorials</li>
				<li>Videos</li>
				<li>Help</li>
			</ul>
			</li>
			<li>
			<h3>First Column</h3>
			<ul class="link-list">
				<li>Hallo</li>
				<li>NExt1</li>
				<li>nExt2</li>
				<li>neXT3</li>
			</ul>
			</li>
		
		</ul>
				<span><?php echo COPY ?> | </span>
				<span><a href="<?php echo URL . 'info/disclaimer'?>">Imprint</a> | </span>
				<span> Follow us </span>
				<span>
					<a href="#"><img id="follow-us" src="<?php echo URL ?>public/img/follow-rss-q.png"></a>
					<a href="#"><img id="follow-us" src="<?php echo URL ?>public/img/follow-twitter.png"></a>
					<a href="#"><img id="follow-us" src="<?php echo URL ?>public/img/follow-fcbk.png"></a>
				</span>
			</div>
		</div>
	</div><!-- main container -->
	</body>
</html>


