<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title><?php echo $this->site_title ?></title>
	<link rel="shortcut icon" href="<?php echo URL ?>public/img/favicon.gif" />
	<link rel="shortcut icon" type="image/gif" href="<?php echo URL ?>public/img/favicon.gif" />
	<link rel="stylesheet" href="<?php echo URL ?>public/css/default.css">
	
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/css/contact_form.css" media="all">
	<script type="text/javascript" src="<?php echo  URL ?>public/js/contact_form.js"></script>

	<script type="text/javascript">document.cookie = "js_enabled=1; expires=0; path=/";</script>
	<script type="text/javascript" src="<?php echo  URL ?>public/js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo  URL ?>public/js/custom.js"></script>
	
<!--[if IE]>
  <style type="text/css">
    .grad-black {
       filter: none;
    }
    #menu-button-box {
		bottom: -1px;/* IE handles height differently, so change subtracting*/
	}
  </style>
<![endif]-->
</head>
<body>
